name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Corre diariamente
  workflow_dispatch:  # También puedes activarlo manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update README with Project Status
        run: |
          # Aquí puedes escribir un script para actualizar el README.
          # Puedes usar GitHub API para obtener el estado del Project y modificar el README.
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/<owner>/<repo>/projects
            # Procesar los datos y actualizar el README.
            
      - name: Commit Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update README with project status"
          git push
