name: Update README with Project Status

on:
  schedule:
    - cron: '0 0 * * *'  # Corre diariamente a medianoche UTC
  workflow_dispatch:  # Permite activar manualmente el workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get project columns
      id: get_columns
      run: |
        # Sustituye <owner> y <repo> Actividad-unidad-2
        PROJECT_ID=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/<owner>/<repo>/projects | \
        jq -r '.[] | select(.name=="Actividad unidad 2") | .id')

        if [ -z "$PROJECT_ID" ]; then
          echo "No se encontró el proyecto con nombre 'Actividad unidad 2'"
          exit 1
        fi

        COLUMNS=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/projects/$PROJECT_ID/columns)

        echo "$COLUMNS" | jq -r '.[] | select(.name=="Realizado") | .id' > column_id.txt

    - name: Get done tasks
      id: get_done_tasks
      run: |
        COLUMN_ID=$(cat column_id.txt)

        if [ -z "$COLUMN_ID" ]; then
          echo "No se encontró la columna 'Realizado'"
          exit 1
        fi

        DONE_TASKS=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/projects/columns/$COLUMN_ID/cards | jq '. | length')

        echo "Total tareas realizadas: $DONE_TASKS" > done_tasks.txt

    - name: Update README
      run: |
        DONE_TASKS=$(cat done_tasks.txt)

        # Edita el README.md para mostrar el número de tareas realizadas
        sed -i "/^### Progreso del proyecto/c\### Progreso del proyecto\nTareas realizadas: ${DONE_TASKS}" README.md

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add README.md
        git commit -m "Actualizar número de tareas realizadas en el README"
        git push
